# Generated by Django 5.1.3 on 2024-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('herb', 'Herb')], max_length=50),
        ),
    ]
